### ISSUE TITLE
Sign release tags when making future releases?

### ISSUE THREAD

**Issue by markmcclain** [jcrist/msgspec#628]
### Question

msgspec is a really nice module. Would it be possible to sign the tag when creating future releases?

**Comment by jcrist** [comment]
Releases are initiated via the github UI - all I do is click the "draft a new release" button [here](https://github.com/jcrist/msgspec/releases) when releasing, fill out the info with a new tag, and hit "Publish Release". CI builds the artifacts for pypi and conda-forge. I'm unlikely to make any amendments to this process if they meaningfully increase the release burden - I'm already strapped for OSS time as it is.

How would you go about adding tag signing to this process? What security threat are you hoping this will mitigate? Why should I amend this process to satisfy your request?

**Comment by dhirschfeld** [comment]
I think there are infinitely higher priorities and this is really just a box-ticking exercise. IME your dependencies not having signed commits/tags isn't going to be the biggest security hole in your organization.

That said, if you did want to sign commits/tags you can add a SSH signing key to your GitHub account with e.g.
```
gh ssh-key add ~/.ssh/id_ed25519.pub --type signing
```
...and configure git to use it with something like:
```
git config --global gpg.format ssh
git config --global user.signingkey "~/.ssh/id_ed25519"
git config --global commit.gpgsign true
git config --global tag.gpgsign true
git config --global gpg.ssh.allowedSignersFile "~/.config/git/allowed_signers"
```
...and you can create the `allowed_signers` file with:
```
echo echo "$(git config --get user.email) $(cat ~/.ssh/id_ed25519.pub)"  >> ~/.config/git/allowed_signers
```

If you create tags via the GitHub UI that won't help you as GitHub creates lightweight tags.
In my own workflow I create signed tags locally and have GitHub actions create a release automatically.

<details>
<summary><b><tt>release.yaml</tt></b></summary>

```yaml
name: github/release
run-name: "[${{ github.ref_name }}] github/release"


on:
  push:
    tags:
      - '*'


permissions:
  contents: write


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_source
        name: Checkout Source
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - id: create_release
        name: Create Release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euox pipefail
          # https://cli.github.com/manual/gh_release_create
          gh release create '${{ github.ref_name }}' \
            --repo='${{ github.repository }}' \
            --title='Release ${{ github.ref_name }}' \
            --generate-notes \
            --draft
```
</details>

> [!Note]
> I'm just adding this for informational purposes, in case you are interested. I'm not actually recommending you spend valuable development time on this!
